### ISSUE TITLE
Problem starting the app after the first usage

### ISSUE THREAD

**Issue by matt-ny** [IBM/rainbow#72]
I installed it from the app store and it worked perfectly the first time I tried it.
But after completing the checklist the first time, it has failed to start, stuck with a blue box cycling through "Preparing WatsonML"  

 I can swipe to the other screens, for the checklist, camera, player, although the camera screen does not show an image and the "Preparing WatsonML" message persists.

I tried uninstalling and reinstalling the app as well.

Using iPhone 6s - iOS 11.3.1
I do have other apps installed using CoreML working OK.

![img_78a3a39af27e-1](https://user-images.githubusercontent.com/11579039/40686372-1a13b7ae-6365-11e8-9ed9-31ac68e58b22.jpeg)

**Comment by matt-ny** [comment]
workaround from David: if you go to the player screen and tap the leaderboard button, itll try to load the leaderboard with a loading indicator instead. going away from this screen dismisses it

That works for me.

**Comment by dokun1** [comment]
We believe we've fixed this issue, and the app is pending an update for v1.1 in the App Store. As soon as it's available, we'll test it and re-visit this.

**Comment by dokun1** [comment]
Fixed by #81
